dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: iz+0cD7QtZZraqbz45FSpqC+cIg27YY5tOC1vr4WcVqSAqnMvFCOtcZDLYIXWuy31iPqKTvBWd9piQ3EP78WZhuuGLaTIgwma/7qPlrwU0Xx3pDviCJmdCI2R7PX73sdJcMU2gj0op+7US05wNuG2L7UQab0ydz6fIq6ymH5/OS1Anlj1RzOghqoLIIYigjYoTNI1oRjBLqFlaZjKzHYh81b0YHNm8OEiSBDzU5KFRGEnNI//4/KmULkfrAqHTbWEUB90YGT16qa/I0e1gXSYQYhESsPoJCKkmYvc1SskTWwvBkHimt9DdXDXdu+LZLl6qnOolqy7fMWLa0sHdIa2ii3p8e/LU97wwBSDVxAi+ycuT/xlx+MwAAI2cGDCF3p3dt920biLv8w3+ZNzJ5pUhIjQpU2LDTP/eTxsKe1TiUnF+rGWua1TzwsPWu61bSXA0oLYS94uVAr8wmmIT/x/EggObpidhX1izh7/xE1BddoW4MTtjavpfcAoMlSC9jJl4w95MLhTWkfSQPJcGvL+ezDVjPwT9OfAhS+1SAU8+ijdOku7uHqdvsSgrOZEa9KR8uux7OeHvlDF2Dbn+NSAW+ZwQF7mcaVfEJ3KaZfLvaZKiQ2C+BkTdjIDrB+4dymwBsFvNx4L75PVfTexFJazZpplTcJvhFWOA2kyiUYtGU=
install:
- pip install -r requirements.txt
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_crickit.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace
  examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-crickit --library_location
  .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
